from django.db.models.signals import post_save
from django.dispatch import receiver
from .models import Provincia, Ciudad

#-----UD6.5-----
# Diccionario de capitales de provincia
PROVINCIA_CAPITALES = {
    "Albacete": "Albacete",
    "Alicante": "Alicante",
    "Almería": "Almería",
    "Badajoz": "Badajoz",
    "Barcelona": "Barcelona",
    "Vizcaya": "Bilbao",
    "Burgos": "Burgos",
    "Cádiz": "Cádiz",
    "Cáceres": "Cáceres",
    "Castellón": "Castellón de la Plana",
    "Ceuta": "Ceuta",
    "Ciudad Real": "Ciudad Real",
    "Córdoba": "Córdoba",
    "Cuenca": "Cuenca",
    "Girona": "Girona",
    "Granada": "Granada",
    "Guadalajara": "Guadalajara",
    "Huelva": "Huelva",
    "Jaén": "Jaén",
    "León": "León",
    "Lleida": "Lleida",
    "La Rioja": "Logroño",
    "Las Palmas": "Las Palmas de Gran Canaria",
    "Lugo": "Lugo",
    "Madrid": "Madrid",
    "Málaga": "Málaga",
    "Melilla": "Melilla",
    "Murcia": "Murcia",
    "Ourense": "Ourense",
    "Asturias": "Oviedo",
    "Palencia": "Palencia",
    "Baleares": "Palma",
    "Navarra": "Pamplona",
    "Salamanca": "Salamanca",
    "Cantabria": "Santander",
    "Santa Cruz de Tenerife": "Santa Cruz de Tenerife",
    "Segovia": "Segovia",
    "Sevilla": "Sevilla",
    "Soria": "Soria",
    "Tarragona": "Tarragona",
    "Teruel": "Teruel",
    "Toledo": "Toledo",
    "Valencia": "Valencia",
    "Valladolid": "Valladolid",
    "Pontevedra": "Vigo",
    "Álava": "Vitoria-Gasteiz",
    "Zamora": "Zamora",
    "Zaragoza": "Zaragoza"
}

CAPITALES = {
    "ALC": "Alicante",
    "ALB": "Albacete",
    "ALM": "Almería",
    "CAD": "Cádiz",
    "CAS": "Castellón de la Plana",
    "COR": "Córdoba",
    "GRA": "Granada",
    "HUE": "Huelva",
    "JAE": "Jaén",
    "MAL": "Málaga",
    "SEV": "Sevilla",
    "TER": "Teruel",
    "VAL": "Valencia",
    "VLL": "Valladolid",
    "VIT": "Vitoria-Gasteiz",
    "ZAM": "Zamora",
    "ZAR": "Zaragoza",
    "BAD": "Badajoz",
    "BAR": "Barcelona",
    "BIL": "Bilbao",
    "BUR": "Burgos",
    "CAC": "Cáceres",
    "CEU": "Ceuta",
    "CIR": "Ciudad Real",
    "CUE": "Cuenca",
    "GIR": "Girona",
    "GUA": "Guadalajara",
    "LEO": "León",
    "LLE": "Lleida",
    "LOG": "Logroño",
    "LPA": "Las Palmas de Gran Canaria",
    "LUG": "Lugo",
    "MAD": "Madrid",
    "MEL": "Melilla",
    "MUR": "Murcia",
    "OUR": "Ourense",
    "OVI": "Oviedo",
    "PAL": "Palencia",
    "PAM": "Pamplona",
    "SAL": "Salamanca",
    "SAN": "Santander",
    "SCG": "Santa Cruz de Tenerife",
    "SEG": "Segovia",
    "SORIA": "Soria",
    "TAR": "Tarragona",
    "TOLE": "Toledo",
    "VIGO": "Vigo",
}

@receiver(post_save, sender=Provincia)
def save_capital(sender, instance, created, **kwargs):
    if created:
        capital_name = PROVINCIA_CAPITALES.get(instance.nombre)
        if capital_name:
            city_code = next((k for k, v in CAPITALES.items() if v == capital_name), None)
            if city_code:
                Ciudad.objects.create(nombre=capital_name, codigo=city_code, provincia=instance)
